phpub.lo: /home/lucas/Code/phpub/ext/phpub.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/phpub.c -o phpub.lo 
kernel/main.lo: /home/lucas/Code/phpub/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /home/lucas/Code/phpub/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /home/lucas/Code/phpub/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/exception.c -o kernel/exception.lo 
kernel/debug.lo: /home/lucas/Code/phpub/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /home/lucas/Code/phpub/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /home/lucas/Code/phpub/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /home/lucas/Code/phpub/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/array.c -o kernel/array.lo 
kernel/string.lo: /home/lucas/Code/phpub/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /home/lucas/Code/phpub/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /home/lucas/Code/phpub/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /home/lucas/Code/phpub/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /home/lucas/Code/phpub/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /home/lucas/Code/phpub/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /home/lucas/Code/phpub/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /home/lucas/Code/phpub/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /home/lucas/Code/phpub/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /home/lucas/Code/phpub/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /home/lucas/Code/phpub/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /home/lucas/Code/phpub/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/kernel/exit.c -o kernel/exit.lo 
phpub/sorting.lo: /home/lucas/Code/phpub/ext/phpub/sorting.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/phpub/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/phpub/ext/phpub/sorting.zep.c -o phpub/sorting.lo 
$(phplibdir)/phpub.la: ./phpub.la
	$(LIBTOOL) --mode=install cp ./phpub.la $(phplibdir)

./phpub.la: $(shared_objects_phpub) $(PHPUB_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_phpub) $(PHPUB_SHARED_LIBADD)

